In [3]:
import numpy as np


In [4]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
#create array of Zeros, ones, custom array
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
print(a.shape)

(3, 3)


In [9]:
## array of constants
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [10]:
d=np.eye(4)   #identity matrix
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0.63815588 0.99920296 0.41484378]
 [0.55681655 0.46906787 0.36328287]]


In [12]:
print(randomMatrix[1,2])

0.3632828741714743


In [14]:
print(randomMatrix[: ,2])

[0.41484378 0.36328287]


In [15]:
randomMatrix[1,1:]=1
print(randomMatrix)

[[0.63815588 0.99920296 0.41484378]
 [0.55681655 1.         1.        ]]


In [23]:
## set some rows and col
z=np.zeros((3,3),dtype=np.int64)
print(z)
z[1,: ]=5
print(z)
z[:,-1] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [5 5 5]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [24]:
print(z.dtype)

int64


In [28]:
## Mathematical Operations on Numpy

x = np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))
print(x-y)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [29]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [30]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [32]:
## matrix multiplication and DOT Products
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [34]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [35]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [38]:
# multiplication of vectors
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a.dot(b))

70


## ^dot product of 2 vectors give scalar

In [39]:
print(sum(a))

10


In [41]:

## ^ sum of all elements of array

In [42]:
print(np.sum(x))

10


In [44]:
print(np.sum(x,axis=0))  ## sum alonng col

[4 6]


In [45]:
print(np.sum(x,axis=1))

[3 7]


In [46]:
## > axis 1
## ^ axis =

In [47]:
## Stacking of arrays
print(a)
b=b**2
print(b)

[1 2 3 4]
[25 36 49 64]


In [48]:
np.stack((a,b),axis=1)

array([[ 1, 25],
       [ 2, 36],
       [ 3, 49],
       [ 4, 64]])

In [51]:
a=np.stack((a,b),axis=0)

In [52]:
print(a)

[[ 1  2  3  4]
 [25 36 49 64]]


In [53]:
a=a.reshape((4,2))

In [54]:
print(a)

[[ 1  2]
 [ 3  4]
 [25 36]
 [49 64]]


In [55]:
a=a.reshape((1,8))

In [56]:
print(a)

[[ 1  2  3  4 25 36 49 64]]


In [57]:
a=a.reshape((8,))

In [58]:
print(a)

[ 1  2  3  4 25 36 49 64]


In [59]:
a=a.reshape((4,-1))
print(a)

[[ 1  2]
 [ 3  4]
 [25 36]
 [49 64]]


In [60]:
a=a.reshape((-1,4))

In [61]:
print(a)

[[ 1  2  3  4]
 [25 36 49 64]]


# Numpy RANDOM MODULE

    - Important when working with random distributions
    - rand
    - randn
    - radient
    - random
    - choice
    - shuffle

In [62]:
#### np.arange() is Not a part of random module, but is stil very important

In [66]:
# will generate numbers from 0 to <10 i.e. 9
a = np.arange(10)
print(a)
a=np.arange(10)+15
print(a)





[0 1 2 3 4 5 6 7 8 9]
[15 16 17 18 19 20 21 22 23 24]


In [74]:
np.random.shuffle(a)
print(a)

[22 21 17 24 19 16 15 20 18 23]


In [75]:
# returns values from standard normal distributtion....widely used
a= np.random.rand(2,3)

In [76]:
print(a)

[[0.66605123 0.76774093 0.25758768]
 [0.46115    0.19424567 0.97095032]]


In [77]:
a= np.random.randint(5,10,3)
print(a)

[7 9 9]


In [89]:
# randomly pick one ele
ele = np.random.choice([1,4,3,2,11,27])
print(ele)

4


In [91]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[7 9 9]


## Some more Numpy Functions - Statistics








    -min
    -max
    -mean
    -median
    -average
    -variance
    -standard deviation
    

In [93]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [95]:
print(np.min(a))
print(np.min(a,axis=0))

0
[1 2 2 0]


In [96]:
print(np.max(a,axis=0))

[7 6 3 4]


In [97]:
print(np.min(a,axis=1))

[1 0]


In [98]:
print(np.max(a,axis=1))

[4 7]


In [102]:
#Mean : ave all ele
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [103]:
## Median : middlemost val
c=np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [104]:
# MEAN vs AVERAGE
print(np.mean(c))

2.4


In [106]:
## AVERAGE is WEIGHTED
wts = np.array([1,2,3,4,5])
print(np.average(c,weights=wts))

2.066666666666667


In [107]:
# if you give wts = then its like mean

In [116]:
## STANDARD DEVIATION
## sigma = root((1/n)*sum(xi-mean)^2)
u=np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.854723699099141


In [117]:
## inbuilt
dev = np.std(c)
print(dev)

1.854723699099141


In [118]:
#Variance
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
